apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: three-tier
  labels:
    app: redis-server
spec:
  type: ClusterIP
  selector:
    app: redis-server
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
