apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.8.1
    helm:
      releaseName: aws-load-balancer-controller
      # IRSA role ARN is deterministic — created by terraform/cluster-addons/alb-controller.tf
      # as "<cluster_name>-alb-controller". Not a secret.
      values: |
        clusterName: 3-tier-cluster
        region: us-east-1
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::640584914236:role/3-tier-cluster-alb-controller
        # Reduce resource requests so this fits on a single c7i-flex.large node.
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
