apiVersion: v1
kind: Service
metadata:
  name: yelb-appserver
  namespace: 3-tier
  labels:
    app: yelb-appserver
spec:
  type: ClusterIP
  selector:
    app: yelb-appserver
  ports:
    - name: http
      port: 4567
      targetPort: 4567
      protocol: TCP
